=== baron-chain/wallet-registry/wallet.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema#",
  "$id": "https://json-schema.org/draft-07/schema",
  "title": "Cosmos Wallet",
  "description": "Cosmos Wallet.json is a metadata file that contains information about a wallet of a specific platform and which chains it supports, either natively or via custom client-side addition.",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "wallet_name": {
      "type": "string",
      "pattern": "[a-z]+"
    },
    "pretty_name": {
      "type": "string"
    },
    "website": {
      "type": "string",
      "format": "url"
    },
    "git_repo": {
      "type": "string",
      "format": "url"
    },
    "supported_chains": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "[a-z0-9]+"
      },
      "minContains": 1
    },
    "features": {
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["suggest_chain", "get_supported_chains", "icns"]
      }
    },
    "platforms": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "device": {
            "type": "string",
            "enum": ["mobile", "tablet", "desktop", "other"]
          },
          "type": {
            "type": "string",
            "enum": ["application", "extension"]
          },
          "platform": {
            "type": "string",
            "enum": [
              "chrome",
              "firefox",
              "ios",
              "android",
              "otherOS",
              "otherBrowser"
            ]
          },
          "install_link": {
            "type": "string",
            "format": "uri"
          }
        },
        "additionalProperties": false,
        "required": ["device", "type", "platform"]
      },
      "minContains": 1
    },
    "images": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "png": {
            "type": "string",
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/wallet-registry/main/(.*)\\.png$"
          },
          "svg": {
            "type": "string",
            "format": "uri-reference",
            "pattern": "^https://raw\\.githubusercontent\\.com/cosmos/wallet-registry/main/(.*)\\.svg$"
          },
          "theme": {
            "type": "object",
            "properties": {
              "primary_color_hex": {
                "type": "string",
                "pattern": "^#[0-9a-fA-F]{6}$"
              },
              "circle": {
                "type": "boolean"
              },
              "dark_mode": {
                "type": "boolean"
              }
            },
            "minProperties": 1,
            "additionalProperties": false
          },
          "layout": {
            "type": "string",
            "enum": ["logo", "logomark", "logotype"],
            "description": "logomark == icon only; logotype == text only; logo == icon + text."
          },
          "text_position": {
            "type": "string",
            "enum": ["top", "bottom", "left", "right", "integrated"],
            "description": "Indicates in which position the text is placed, in case the layout is 'icon' type, it's required only in this case."
          }
        },
        "if": {
          "properties": {
            "layout": { "const": "logo" }
          },
          "required": ["layout"]
        },
        "then": {
          "required": ["text_position"]
        },
        "anyOf": [
          {
            "required": ["png"]
          },
          {
            "required": ["svg"]
          }
        ],
        "required": ["layout"],
        "additionalProperties": false
      }
    },
    "wallet_connect": {
      "type": "object",
      "properties": {
        "deeplink": {
          "type": "object",
          "description": "define all the properties related to deeplink functionality.",
          "properties": {
            "path": {
              "type": "object",
              "description": "it is the path of the deelink URL that will trigger wallet connect actions within a mobile wallet.",
              "properties": {
                "ios": {
                  "type": "string"
                },
                "android": {
                  "type": "string"
                },
                "universal": {
                  "type": "string"
                }
              }
            }
          }
        }
      }
    },
    "mobile": {
      "type": "object",
      "properties": {
        "android": {
          "type": "object",
          "properties": {
            "packageName": {
              "type": "string",
              "description": "The package name for your Android standalone app. You make it up, but it needs to be unique on the Play Store. See this [StackOverflow question](https://stackoverflow.com/questions/6273892/android-package-name-convention)."
            },
            "schema": {
              "type": "string",
              "description": "Custom schema that provide a way to reference resources inside an app, documented [here](https://developer.android.com/training/app-links/deep-linking)."
            },
            "universalSchema": {
              "type": "string",
              "description": "Universal schema for universal deeplink that provide a way to reference resources inside an app, documented [here](https://developer.android.com/training/app-links)."
            }
          }
        },
        "ios": {
          "type": "object",
          "properties": {
            "bundleIdentifier": {
              "type": "string",
              "description": "The bundle identifier for your iOS standalone app. You make it up, but it needs to be unique on the App Store. See this [StackOverflow question](https://stackoverflow.com/questions/11347470/what-does-bundle-identifier-mean-in-an-ios-project)."
            },
            "schema": {
              "type": "string",
              "description": "Custom URL schemes provide a way to reference resources inside an app, documented [here](https://developer.apple.com/documentation/xcode/defining-a-custom-url-scheme-for-your-app)."
            },
            "universalSchema": {
              "type": "string",
              "description": "Universal schema for universal deeplink that provide a way to reference resources inside an app, documented [here](https://developer.apple.com/ios/universal-links/)."
            }
          }
        }
      }
    }
  },
  "additionalProperties": false,
  "required": [
    "$schema",
    "wallet_name",
    "pretty_name",
    "platforms",
    "supported_chains",
    "images"
  ]
}

=== baron-chain/wallet-registry/wallets/keplrmobile/wallet.json
{
  "$schema": "../../wallet.schema.json",
  "wallet_name": "keplrmobile",
  "pretty_name": "Keplr",
  "website": "https://www.keplr.app/",
  "git_repo": "https://github.com/chainapsis/keplr-wallet",
  "supported_chains": [
    "cosmoshub",
    "osmosis",
    "secretnetwork",
    "regen",
    "akash",
    "sifchain",
    "stargaze",
    "sentinel",
    "persistence",
    "cryptoorgchain",
    "irisnet",
    "agoric",
    "axelar",
    "certik",
    "ixo",
    "emoney",
    "tick",
    "terra",
    "likecoin",
    "bitcanna",
    "bitsong",
    "ki",
    "panacea",
    "juno",
    "sommelier",
    "umee",
    "evmos",
    "injective",
    "bostrom",
    "comdex",
    "cheqd",
    "chihuahua",
    "lumnetwork",
    "vidulum",
    "desmos",
    "dig",
    "starname",
    "gravitybridge"
  ],
  "features": ["icns"],
  "platforms": [
    {
      "device": "mobile",
      "type": "application",
      "platform": "ios",
      "install_link": "https://apps.apple.com/app/keplr-wallet/id1567851089"
    },
    {
      "device": "mobile",
      "type": "application",
      "platform": "android",
      "install_link": "https://play.google.com/store/apps/details?id=com.chainapsis.keplr"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/keplrextension/images/logo.png",
      "svg": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/keplrextension/images/logo.svg",
      "theme": {
        "primary_color_hex": "#1BB8FF",
        "circle": false,
        "dark_mode": false
      },
      "layout": "logomark"
    },
    {
      "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/keplrextension/images/logo-text.png",
      "svg": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/keplrextension/images/logo-text.svg",
      "theme": {
        "primary_color_hex": "#EBF7FD",
        "circle": false,
        "dark_mode": false
      },
      "layout": "logo",
      "text_position": "right"
    },
    {
      "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/keplrextension/images/logo-text-dark.png",
      "svg": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/keplrextension/images/logo-text-dark.svg",
      "theme": {
        "primary_color_hex": "#0A0718",
        "circle": false,
        "dark_mode": true
      },
      "layout": "logomark"
    }
  ],
  "wallet_connect": {
    "deeplink": {
      "path": {
        "android": "wcV2",
        "ios": "wcV2"
      }
    }
  },
  "mobile": {
    "ios": {
      "bundle_identifier": "com.chainapsis.keplrwallet",
      "schema": "keplrwallet"
    },
    "android": {
      "package_name": "com.chainapsis.keplr",
      "schema": "keplrwallet"
    }
  }
}

=== baron-chain/wallet-registry/wallets/trustwalletmobile/wallet.json
{
  "$schema": "../../wallet.schema.json",
  "wallet_name": "trustwalletmobile",
  "pretty_name": "Trust Wallet",
  "website": "https://www.trustwallet.com",
  "git_repo": "https://github.com/trustwallet",
  "supported_chains": [
    "cosmoshub",
    "osmosis",
    "cryptoorgchain",
    "terra",
    "evmos",
    "kava",
    "thorchain"
  ],
  "platforms": [
    {
      "device": "mobile",
      "type": "application",
      "platform": "ios",
      "install_link": "https://apps.apple.com/app/apple-store/id1288339409"
    },
    {
      "device": "mobile",
      "type": "application",
      "platform": "android",
      "install_link": "https://play.google.com/store/apps/details?id=com.wallet.crypto.trustapp"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/trustwalletmobile/images/logo-text.png",
      "svg": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/trustwalletmobile/images/logo-text.svg",
      "theme": {
        "primary_color_hex": "#0500ff",
        "circle": false,
        "dark_mode": false
      },
      "layout": "logo",
      "text_position": "right"
    },
    {
      "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/trustwalletmobile/images/logo.png",
      "svg": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/trustwalletmobile/images/logo.svg",
      "theme": {
        "primary_color_hex": "#0500ff",
        "circle": false,
        "dark_mode": false
      },
      "layout": "logo",
      "text_position": "top"
    }
  ]
}

=== baron-chain/wallet-registry/wallets/leapextension/wallet.json
{
  "$schema": "../../wallet.schema.json",
  "wallet_name": "leapextension",
  "pretty_name": "Leap Cosmos Wallet",
  "website": "https://www.leapwallet.io/",
  "git_repo": "",
  "supported_chains": [
    "cosmoshub",
    "juno",
    "osmosis",
    "secretnetwork",
    "agoric",
    "akash",
    "assetmantle",
    "axelar",
    "bitsong",
    "cheqd",
    "chihuahua",
    "comdex",
    "desmos",
    "emoney",
    "evmos",
    "fetchhub",
    "gravitybridge",
    "injective",
    "irisnet",
    "jackal",
    "kujira",
    "likecoin",
    "persistence",
    "atlantic",
    "sifchain",
    "sommelier",
    "stargaze",
    "starname",
    "stride",
    "teritori",
    "umee"
  ],
  "features": ["suggest_chain"],
  "platforms": [
    {
      "device": "desktop",
      "type": "extension",
      "platform": "chrome",
      "install_link": "https://chrome.google.com/webstore/detail/leap-cosmos-wallet/fcfcfllfndlomdhbehjjcoimbgofdncg"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/leapextension/images/logo.png",
      "svg": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/leapextension/images/logo.svg",
      "theme": {
        "primary_color_hex": "#32DA6D",
        "circle": false,
        "dark_mode": false
      },
      "layout": "logomark"
    }
  ]
}

=== baron-chain/wallet-registry/wallets/xdefiextension/wallet.json
{
    "$schema": "../../wallet.schema.json",
    "wallet_name": "xdefiextension",
    "pretty_name": "xDefi",
    "website": "https://www.xdefi.io/",
    "git_repo": "",
    "supported_chains": [
      "cosmoshub",
      "axelar",
      "osmosis",
      "stride",
      "mars",
      "stargaze",
      "crescent",
      "sei",
      "kujira",
      "cryptoorgchain",
      "kava",
      "akash",
      "juno",
      "terra2"
    ],
    "features": ["suggest_chain"],
    "platforms": [
      {
        "device": "desktop",
        "type": "extension",
        "platform": "chrome",
        "install_link": "https://chrome.google.com/webstore/detail/xdefi-wallet/hmeobnfnfcmdkdcmlblgagmfpfboieaf"
      }
    ],
    "images": [
      {
        "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/xdefiextension/images/logo.png",
        "theme": {
          "primary_color_hex": "#4476f2",
          "circle": false,
          "dark_mode": false
        },
        "layout": "logomark"
      }
    ]
  }

=== baron-chain/wallet-registry/wallets/keplrextension/wallet.json
{
  "$schema": "../../wallet.schema.json",
  "wallet_name": "keplrextension",
  "pretty_name": "Keplr",
  "website": "https://www.keplr.app/",
  "git_repo": "https://github.com/chainapsis/keplr-wallet",
  "supported_chains": [
    "cosmoshub",
    "osmosis",
    "secretnetwork",
    "regen",
    "akash",
    "sifchain",
    "stargaze",
    "sentinel",
    "persistence",
    "kava",
    "cryptoorgchain",
    "irisnet",
    "agoric",
    "axelar",
    "certik",
    "ixo",
    "emoney",
    "juno",
    "sommelier",
    "umee",
    "evmos",
    "bostrom",
    "starname",
    "gravitybridge",
    "stride",
    "tgrade"
  ],
  "features": ["suggest_chain", "icns"],
  "platforms": [
    {
      "device": "desktop",
      "type": "extension",
      "platform": "chrome",
      "install_link": "https://chrome.google.com/webstore/detail/keplr/dmkamcknogkgcdfhhbddcghachkejeap"
    },
    {
      "device": "desktop",
      "type": "extension",
      "platform": "firefox",
      "install_link": "https://addons.mozilla.org/firefox/addon/keplr/"
    }
  ],
  "images": [
    {
      "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/keplrextension/images/logo.png",
      "svg": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/keplrextension/images/logo.svg",
      "theme": {
        "primary_color_hex": "#1BB8FF",
        "circle": false,
        "dark_mode": false
      },
      "layout": "logomark"
    },
    {
      "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/keplrextension/images/logo-text.png",
      "svg": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/keplrextension/images/logo-text.svg",
      "theme": {
        "primary_color_hex": "#EBF7FD",
        "circle": false,
        "dark_mode": false
      },
      "layout": "logo",
      "text_position": "right"
    },
    {
      "png": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/keplrextension/images/logo-text-dark.png",
      "svg": "https://raw.githubusercontent.com/cosmos/wallet-registry/main/wallets/keplrextension/images/logo-text-dark.svg",
      "theme": {
        "primary_color_hex": "#0A0718",
        "circle": false,
        "dark_mode": true
      },
      "layout": "logomark"
    }
  ]
}
